// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkyHelp.Context;

#nullable disable

namespace SkyHelp.Migrations
{
    [DbContext(typeof(SkyHelpContext))]
    partial class SkyHelpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkyHelp.Domiciliarios", b =>
                {
                    b.Property<Guid>("IdDomiciliario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EstadoActividad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("IDUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdDomiciliario");

                    b.HasIndex("IDUsuario")
                        .IsUnique();

                    b.ToTable("Domiciliarios", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Auditoria", b =>
                {
                    b.Property<Guid>("IDLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IDRegistro")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDLog");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.EstadosTicket", b =>
                {
                    b.Property<Guid>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdEstado");

                    b.HasIndex("NombreEstado")
                        .IsUnique();

                    b.ToTable("EstadosTickets", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstado = new Guid("66666666-6666-6666-6666-666666666666"),
                            Descripcion = "Ticket recién creado, aún sin atender.",
                            NombreEstado = "Abierto"
                        },
                        new
                        {
                            IdEstado = new Guid("77777777-7777-7777-7777-777777777777"),
                            Descripcion = "Ticket en espera de diagnóstico o de una acción posterior.",
                            NombreEstado = "Pendiente"
                        },
                        new
                        {
                            IdEstado = new Guid("88888888-8888-8888-8888-888888888888"),
                            Descripcion = "El pedido asociado al ticket se está preparando para su entrega.",
                            NombreEstado = "En preparacion"
                        },
                        new
                        {
                            IdEstado = new Guid("99999999-9999-9999-9999-999999999999"),
                            Descripcion = "El domiciliario va en camino a entregar el pedido.",
                            NombreEstado = "En ruta"
                        },
                        new
                        {
                            IdEstado = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Descripcion = "El ticket fue atendido y cerrado.",
                            NombreEstado = "Resuelto"
                        });
                });

            modelBuilder.Entity("SkyHelp.Models.ProgresoTickets", b =>
                {
                    b.Property<Guid>("IdProgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdTecnico")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTicket")
                        .HasColumnType("uuid");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("integer");

                    b.HasKey("IdProgreso");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("IdTicket");

                    b.ToTable("ProgresoTickets", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Reportes", b =>
                {
                    b.Property<Guid>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Datos")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdOrigen")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("OrigenTabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reportes", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Roles", b =>
                {
                    b.Property<Guid>("IDRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IDRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            IDRol = new Guid("11111111-1111-1111-1111-111111111111"),
                            Descripcion = "Administrador del sistema, con acceso total.",
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IDRol = new Guid("22222222-2222-2222-2222-222222222222"),
                            Descripcion = "Técnico encargado del diagnóstico y soporte de tickets.",
                            NombreRol = "Tecnico"
                        },
                        new
                        {
                            IDRol = new Guid("33333333-3333-3333-3333-333333333333"),
                            Descripcion = "Domiciliario encargado de la entrega de pedidos.",
                            NombreRol = "Domiciliario"
                        },
                        new
                        {
                            IDRol = new Guid("44444444-4444-4444-4444-444444444444"),
                            Descripcion = "Cliente que reporta tickets de soporte.",
                            NombreRol = "Usuario"
                        });
                });

            modelBuilder.Entity("SkyHelp.Models.Tickets", b =>
                {
                    b.Property<Guid>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FallaEncontrada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDiagnostico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdDomiciliario")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdEstado")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdTecnico")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumeroTicket"));

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PruebasRealizadas")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Recomendaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdTicket");

                    b.HasIndex("IdDomiciliario");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTecnico");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("NumeroTicket")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Models.Usuarios", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreUsuarios")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("55555555-5555-5555-5555-555555555555"),
                            Contrasena = "$2a$11$iZtHw38ztzeNAfWiTfmQ9e8aig.dwYG/xb60VDRNYgZI5UKIPIemO",
                            Correo = "admin@skyhelp.com",
                            EstadoCuenta = "Activo",
                            IdRol = new Guid("11111111-1111-1111-1111-111111111111"),
                            NombreCompleto = "Administrador SkyHelp",
                            NombreUsuarios = "admin"
                        });
                });

            modelBuilder.Entity("SkyHelp.Pedidos", b =>
                {
                    b.Property<Guid>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdDomiciliario")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdTicket")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumeroPedido"));

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdDomiciliario");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("NumeroPedido")
                        .IsUnique();

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Tecnicos", b =>
                {
                    b.Property<Guid>("IdTecnico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.HasKey("IdTecnico");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Tecnicos", (string)null);
                });

            modelBuilder.Entity("SkyHelp.Domiciliarios", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Domiciliarios")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Auditoria", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.ProgresoTickets", b =>
                {
                    b.HasOne("SkyHelp.Tecnicos", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IdTecnico");

                    b.HasOne("SkyHelp.Models.Tickets", "Ticket")
                        .WithMany("ProgresoTickets")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnico");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SkyHelp.Models.Reportes", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Tickets", b =>
                {
                    b.HasOne("SkyHelp.Domiciliarios", "Domiciliario")
                        .WithMany("Tickets")
                        .HasForeignKey("IdDomiciliario");

                    b.HasOne("SkyHelp.Models.EstadosTicket", "EstadoTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyHelp.Tecnicos", "Tecnico")
                        .WithMany("Tickets")
                        .HasForeignKey("IdTecnico");

                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Tickets")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domiciliario");

                    b.Navigation("EstadoTicket");

                    b.Navigation("Tecnico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Usuarios", b =>
                {
                    b.HasOne("SkyHelp.Models.Roles", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SkyHelp.Pedidos", b =>
                {
                    b.HasOne("SkyHelp.Domiciliarios", "Domiciliario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdDomiciliario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domiciliario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Tecnicos", b =>
                {
                    b.HasOne("SkyHelp.Models.Usuarios", "Usuario")
                        .WithMany("Tecnico")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Domiciliarios", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SkyHelp.Models.EstadosTicket", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SkyHelp.Models.Roles", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkyHelp.Models.Tickets", b =>
                {
                    b.Navigation("ProgresoTickets");
                });

            modelBuilder.Entity("SkyHelp.Models.Usuarios", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Domiciliarios");

                    b.Navigation("Pedidos");

                    b.Navigation("Reportes");

                    b.Navigation("Tecnico");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SkyHelp.Tecnicos", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
